### PR TITLE
Refactors the completion handler

### PR DESCRIPTION
**Pull request by sprejjs**

### CODE REVIEW

**Comment by tuanlung** [comment]
Hi Vlad, 
Thanks for the suggestion.
I left some comments on your changes, could you please review it?
I think this code change doesn't achieve the original intent.

Thank you very much.
Tuan-Lung

**Comment by sprejjs** [comment]
Hi Tuan-Lung, I don't see your comments. Could you show me where you left them, please?

**Comment by tuanlung** [comment]
Hi Vlad,

Sorry for the late response.
The comments were in "Files changed" tab, hope you can see it.

In case it's not showing on your side, I'm pasting the comments below:

--- original comments on line 145 and 146 ---
Hi Vlad,
Thanks for the refactor suggestion.
But I think this doesn't do the same thing as the original completionWithItemsHandler.

Specifically, the original intent was to save the newMeme only when an activity is chosen by the user in activityView.
When users tap Cancel in activityView, your code change will still save the newMeme while the user wants to drop the newMeme.

Could you please suggest how can we better achieve the original intent?

Thank you very much.
Tuan-Lung
--- end of original comments ---

Thank you again, Vlad.

Tuan-Lung

**Comment by sprejjs** [comment]
Hi Tuan-Lung,

Right, yes, I misunderstood you. 

In this case, your original code is probably the most straightforward way to go around this, which is not a bad thing, because your users will not be able to interact with your application in the meanwhile anyway as they are engaged in the sharing dialog of the operating system itself.

**Comment by tuanlung** [comment]
Hi Vlad,

I see. Thanks for the comments.
According to your comments, I will leave the code as is.

Thanks again.
Tuan-Lung

**Pull request closed without merging**
